wandb_version: 1

in_channels:
  desc: null
  value: 1
hidden_dim:
  desc: null
  value: 128
residual_hidden_dim:
  desc: null
  value: 32
num_residual_layers:
  desc: null
  value: 2
embedding_dim:
  desc: null
  value: 64
num_embeddings:
  desc: null
  value: 256
learning_rate:
  desc: null
  value: 0.0002
batch_size:
  desc: null
  value: 16
architecture:
  desc: null
  value: VAE
dataset:
  desc: null
  value: ESC50
epochs:
  desc: null
  value: 50
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713327990.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
